//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWindows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAO
    {
        public int STT { get; set; }
        public string NhanXet { get; set; }
        public string TaiLieu { get; set; }
        public string MaDeTai { get; set; }
    
        public virtual DETAI DETAI { get; set; }
    }
}
