//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWindows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETAI()
        {
            this.BAOCAOs = new HashSet<BAOCAO>();
            this.SINHVIENs = new HashSet<SINHVIEN>();
        }
    
        public string MaDeTai { get; set; }
        public string TenDeTai { get; set; }
        public string LoaiDeTai { get; set; }
        public Nullable<int> Solan { get; set; }
        public Nullable<System.DateTime> TGBD { get; set; }
        public Nullable<System.DateTime> TGKT { get; set; }
        public string MaGV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOCAO> BAOCAOs { get; set; }
        public virtual GIAOVIEN GIAOVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SINHVIEN> SINHVIENs { get; set; }
        public override string ToString()
        {
            return MaDeTai;
        }
    }
}
